version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: jobqueue_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-jobqueue}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-jobqueue_secret}
      POSTGRES_DB: ${POSTGRES_DB:-jobqueue_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-jobqueue} -d ${POSTGRES_DB:-jobqueue_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - jobqueue_network

  redis:
    image: redis:7-alpine
    container_name: jobqueue_redis
    restart: unless-stopped
    command: >
      redis-server
      --save 60 1
      --loglevel warning
      --maxmemory 256mb
      --maxmemory-policy noeviction
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - jobqueue_network

  # api e worker serão adicionados na Etapa 4
  # com build: context e depends_on dos healthchecks acima

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  jobqueue_network:
    driver: bridge